### ISSUE TITLE
0.11

### ISSUE THREAD

**Issue by insin** [insin/newforms#64]
- [x] Remove `render()`, `asDiv()`, `asTable()` and `asUl()`.
- [x] Deprecate `formsetFactory()`
  - [x] Rename `BaseFormSet` to `FormSet`
  - [x] `FormSet` constructor can be used directly or `.extend()`ed to set defaults which used to be passed to `formsetFactory()`.
- [x] Modularise - break everything into individual modules
  - [x] Default `require('newforms')` will still give you a grab-bag of everything
  - [x] Publish to npm as flattened modules - people who want to save on dependency file size when bundling can directly import only what they need - in particular, you should never need to bundle FormSets if you're not using them.
- [x] Populate `form.files` and `cleanedDat`a with `File` objects on the client (#61)
  - [x] API docs
- [x] `MultipleFileField`
- [x] Add a new core `Field` property: `field.widgetAttrs` (#62, #63)
  - [x] Rename `Field.prototype.widgetAttrs` to `getWidgetAttrs`
  - [x] Return `field.widgetAttrs` by default
  - [x] Make sure overrides of `getWidgetAttrs` are calling super() properly
- [x] Don't restrict widget attrs defaulted by numeric fields based on widget type (#59)
- [x] Start `UPGRADE_GUIDE.md` with features removed in this release and deprecated for removal in the next release.

**Comment by marr** [comment]
Looks like #61 landed, which can close "Populate form.files and cleanedData with File objects on the client". Does this mean that .11 is ready to go?

I am looking forward to the widgetAttrs feature. I believe that will let me change the input type? Ie, I'd like to use type="tel" to get the keypad on mobile web for numeric inputs.

Cheers,
Dave

**Comment by insin** [comment]
0.11 is almost ready. just want to play with the client-side `File` object change a bit first.

`widgetAttrs` is at the bottom of the stack in terms of precedence (`widget.attrs` < `render()`-generated attrs < attrs passed to `render()` via `BoundField`) so it won't let you override `type`.

`TextInput` treats the `type` attr specially to allow you to override the rendered type when creating an instance ( `TextInput({attrs: {type: 'tel'}})` ), or you could extend it to create your own widget constructor ( `var TelInput = TextInput.extend({inputType: 'tel'})` )
